/** CareCliQ Worker Mobile UI Spec v2 — CSS variable tokens (light/dark via index.css) */
export const WM = {
  pink: "var(--wm-pink)",
  purple: "var(--wm-purple)",
  amber: "var(--wm-amber)",
  red: "var(--wm-red)",
  green: "var(--wm-green)",
  bg: "var(--wm-bg)",
  surface: "var(--wm-surface)",
  border: "var(--wm-border)",
  text: "var(--wm-text)",
  muted: "var(--wm-muted)",
  clockedInBg: "var(--wm-clocked-in-bg)",
  clockedInBorder: "var(--wm-clocked-in-border)",
  clockedInText: "var(--wm-clocked-in-text)",
  clockedInIcon: "var(--wm-clocked-in-icon)",
  warnBg: "var(--wm-warn-bg)",
  warnBorder: "var(--wm-warn-border)",
  warnText: "var(--wm-warn-text)",
  warnTitle: "var(--wm-warn-title)",
  alertBg: "var(--wm-alert-bg)",
  alertBorder: "var(--wm-alert-border)",
  alertText: "var(--wm-alert-text)",
  alertIcon: "var(--wm-alert-icon)",
  infoBg: "var(--wm-info-bg)",
  infoBorder: "var(--wm-info-border)",
  infoTitle: "var(--wm-info-title)",
  chipGreenBg: "var(--wm-chip-green-bg)",
  chipGreenBorder: "var(--wm-chip-green-border)",
  checkboxBorder: "var(--wm-checkbox-border)",
  taskActiveBg: "var(--wm-task-active-bg)",
  taskDoneText: "var(--wm-task-done-text)",
  missingBg: "var(--wm-missing-bg)",
} as const;
