FROM node:22-bookworm-slim

WORKDIR /app

ENV PNPM_HOME="/pnpm" \
    PATH="/pnpm:$PATH" \
    NODE_ENV=development \
    PORT=3000

RUN corepack enable

COPY . .

RUN corepack pnpm install --frozen-lockfile

EXPOSE 3000

CMD ["corepack", "pnpm", "--filter", "@workspace/frontend", "run", "dev"]
